"""Search checklist task definitions."""

SEARCH_ITEMS = [
    {
        "id": 5,
        "order": 0,
        "label": "Set a budget",
        "explanation": "Set your budget range, income, and down payment so search results match what you can afford.",
        "bullets": [
            "Set your min and max home price range.",
            "Enter your gross income and down payment for an affordability estimate.",
        ],
        "resource": None,
        "component_key": "set_budget",
        "completion_requires_submit": True,
        "allow_unordered_check": True,
        "selectable_when": {"kind": "all_items_checked", "item_ids": [1]},
        "parallel_step_group": "search_parallel_integrations",
    },
    {
        "id": 4,
        "order": 1,
        "label": "Choose search area",
        "explanation": "Add work, family, or other important locations and set your commute range. The map shows your search area (isochrones) based on these locations.",
        "bullets": [
            "Add addresses for work, school, or family.",
            "Set how many minutes you're willing to commute from each location.",
        ],
        "resource": None,
        "component_key": "choose_areas",
        "completion_requires_submit": True,
        "allow_unordered_check": True,
        "selectable_when": {"kind": "all_items_checked", "item_ids": [1]},
        "parallel_step_group": "search_parallel_integrations",
    },
    {
        "id": 2,
        "order": 2,
        "label": "Define your criteria and prioritize needs vs. wants",
        "explanation": "Create a clear list of what you must have in a home versus what would be nice to have.",
        "bullets": [
            "Identify dealbreakers like the number of bedrooms or maximum commute time.",
            "List nice-to-haves such as a pool, specific architectural style, or hardwood floors.",
        ],
        "resource": None,
        "component_key": "define_criteria",
        "completion_requires_submit": True,
        "allow_unordered_check": True,
        "selectable_when": {"kind": "all_items_checked", "item_ids": [1]},
        "parallel_step_group": "search_parallel_integrations",
    },
    {
        "id": 1,
        "order": 3,
        "label": "Get pre-approved for a mortgage",
        "explanation": "Secure a pre-approval letter from a lender to know your exact budget and prove you are a serious buyer.",
        "bullets": [
            "Gather your financial documents like W-2s, pay stubs, and bank statements.",
            "Compare rates from multiple lenders to find the best terms.",
        ],
        "resource": None,
    },
    {
        "id": 3,
        "order": 4,
        "label": "Partner with a real estate agent",
        "explanation": "Hire a buyer's agent to guide you through the search, provide market insights, and give you access to the MLS.",
        "suggested_form_ids": ["aba_disclosure_english", "dual_agency_consent"],
        "bullets": [
            "Ask for referrals and interview a few agents to find a good fit.",
            "Let them set up automated alerts for properties matching your criteria.",
        ],
        "resource": None,
        "component_key": "partner_agent",
        "completion_requires_submit": True,
    },
    {
        "id": 6,
        "order": 5,
        "label": "Sign buyer-broker representation agreement",
        "explanation": "Formalize your relationship with your agent by signing a buyer-broker agreement that defines representation terms, compensation, and duration.",
        "suggested_form_ids": [
            "buyer_broker_exclusive",
            "buyer_broker_non_exclusive",
            "buyer_broker_single_property",
        ],
        "forms_card_variant": "document",
        "completion_type": "signature_based",
        "bullets": [
            "Review the agreement type: exclusive, non-exclusive, or single-property representation.",
            "Understand the compensation structure and how your agent will be paid.",
            "Clarify the duration of the agreement and any termination clauses.",
        ],
        "resource": None,
    },
]
