import type { LucideProps } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Asterisk,
  BarChart2,
  Bath,
  Bed,
  Bookmark,
  Bot,
  Building,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardCheck,
  Clock,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileImage,
  FileSignature,
  FileText,
  Flag,
  FolderLock,
  Footprints,
  GitCompare,
  GraduationCap,
  Grid3X3,
  Handshake,
  Heart,
  Home,
  Inbox,
  Info,
  Key,
  Library,
  Lightbulb,
  Link2,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Minus,
  MoreHorizontal,
  Pencil,
  Phone,
  Plus,
  Receipt,
  RefreshCw,
  Save,
  Search,
  Send,
  SendHorizontal,
  Settings2,
  Share,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  Users,
  UtensilsCrossed,
  Video,
  Volume2,
  VolumeX,
  X,
  XCircle,
} from "lucide-react";

import type { IconName } from "packages/ui/types/icons";

const ICONS: Record<IconName, React.ComponentType<Omit<LucideProps, "ref">>> = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  asterisk: Asterisk,
  "bar-chart-2": BarChart2,
  bath: Bath,
  bed: Bed,
  bookmark: Bookmark,
  bot: Bot,
  building: Building,
  "building-2": Building2,
  calendar: Calendar,
  check: Check,
  "check-circle": CheckCircle,
  "check-circle-2": CheckCircle2,
  "check-square": CheckSquare,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "clipboard-check": ClipboardCheck,
  clock: Clock,
  copy: Copy,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  download: Download,
  edit: Edit,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-image": FileImage,
  "file-signature": FileSignature,
  "file-text": FileText,
  flag: Flag,
  "folder-lock": FolderLock,
  footprints: Footprints,
  "git-compare": GitCompare,
  "graduation-cap": GraduationCap,
  "grid-3x3": Grid3X3,
  handshake: Handshake,
  heart: Heart,
  home: Home,
  inbox: Inbox,
  info: Info,
  key: Key,
  lightbulb: Lightbulb,
  library: Library,
  "link-2": Link2,
  "loader-2": Loader2,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  minus: Minus,
  "more-horizontal": MoreHorizontal,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  receipt: Receipt,
  "refresh-cw": RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  "send-horizontal": SendHorizontal,
  settings: Settings2,
  "settings-2": Settings2,
  share: Share,
  shield: Shield,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  target: Target,
  trash: Trash2,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  "utensils-crossed": UtensilsCrossed,
  video: Video,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  x: X,
  "x-circle": XCircle,
};

export function getIcon(name: IconName): React.ComponentType<Omit<LucideProps, "ref">> | undefined {
  return ICONS[name];
}
