# Re-export all config constants so app.config and _config can import from .constants
from ._constants_api import API_VERSION
from ._constants_aws import S3_BUCKET_NAME_PDFS, S3_PRESIGNED_URL_EXPIRATION_DEFAULT
from ._constants_cors import DEV_CORS_ORIGINS_DEFAULT, PROD_CORS_ORIGINS_DEFAULT
from ._constants_docusign import (
    DOCUSIGN_ACCOUNT_ID_DEFAULT,
    DOCUSIGN_BASE_URL_DEFAULT,
    DOCUSIGN_IMPERSONATED_USER_ID_DEFAULT,
    DOCUSIGN_OAUTH_AUTHORIZATION_URL_DEMO,
    DOCUSIGN_OAUTH_AUTHORIZATION_URL_PROD,
    DOCUSIGN_OAUTH_TOKEN_URL_DEMO,
    DOCUSIGN_OAUTH_TOKEN_URL_PROD,
    DOCUSIGN_SENDER_VIEW_PATH,
    DOCUSIGN_SIGNING_COMPLETE_PATH,
)
from ._constants_google import GOOGLE_CLIENT_ID, GOOGLE_SCOPES
from ._constants_hosts import EC2_HOST
from ._constants_timeouts import (
    AWS_COGNITO_TIMEOUT,
    HTTP_TIMEOUT,
    REQUEST_TIMEOUT,
    SEND_FILE_MAX_AGE_DEFAULT,
)
from ._constants_uploads import (
    ALLOWED_FILE_TYPES_DEFAULT,
    MAX_CONTENT_LENGTH_DEFAULT,
    UPLOAD_FOLDER_DEFAULT,
)

__all__ = [
    "API_VERSION",
    "S3_BUCKET_NAME_PDFS",
    "S3_PRESIGNED_URL_EXPIRATION_DEFAULT",
    "DEV_CORS_ORIGINS_DEFAULT",
    "PROD_CORS_ORIGINS_DEFAULT",
    "DOCUSIGN_ACCOUNT_ID_DEFAULT",
    "DOCUSIGN_BASE_URL_DEFAULT",
    "DOCUSIGN_IMPERSONATED_USER_ID_DEFAULT",
    "DOCUSIGN_OAUTH_AUTHORIZATION_URL_DEMO",
    "DOCUSIGN_OAUTH_AUTHORIZATION_URL_PROD",
    "DOCUSIGN_OAUTH_TOKEN_URL_DEMO",
    "DOCUSIGN_OAUTH_TOKEN_URL_PROD",
    "DOCUSIGN_SENDER_VIEW_PATH",
    "DOCUSIGN_SIGNING_COMPLETE_PATH",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_SCOPES",
    "EC2_HOST",
    "AWS_COGNITO_TIMEOUT",
    "HTTP_TIMEOUT",
    "REQUEST_TIMEOUT",
    "SEND_FILE_MAX_AGE_DEFAULT",
    "ALLOWED_FILE_TYPES_DEFAULT",
    "MAX_CONTENT_LENGTH_DEFAULT",
    "UPLOAD_FOLDER_DEFAULT",
]
