#!/usr/bin/env sh
# Fetch AWS Secrets Manager items and rewrite ./.env for local dev.
# Usage:
#   ./scripts/load-all-secrets.sh [region] [profile]
#
# Behavior:
# - If AWS_* env vars are not set and no profile is given, will source ./.aws.env.
# - Each secret may be:
#     (a) flat JSON object -> expands to KEY=VALUE lines
#     (b) dotenv text -> KEY=VALUE lines (even if \n-escaped in SecretString)
#     (c) scalar -> falls back to SECRET_NAME=<value>
# - Rewrites ./.env

set -eu

DEFAULT_SECRETS="
db_url
AWS_Access
cognito
gmaps
google_calendar
census_api
mapbox
openai
perplexity
plaid
serp
rapidapi
docusign
"

REGION="${1:-${AWS_REGION:-us-east-2}}"
PROFILE="${2:-${AWS_PROFILE:-}}"

log() { printf '%s\n' "$*" >&2; }
die() { printf 'Error: %s\n' "$*" >&2; }
have_cmd() { command -v "$1" >/dev/null 2>&1; }

# ---- parsing helpers ----

# jq JSON -> KEY=VALUE lines (flat object)
json_to_env_lines() {
  if have_cmd jq; then
    jq -r 'if type=="object" then to_entries[]|"\(.key)=\"\(.value|tostring)\"" else empty end'
  else
    python3 - <<'PY'
import sys,json
try:
    obj=json.load(sys.stdin)
except Exception:
    sys.exit(0)
if isinstance(obj, dict):
    for k,v in obj.items():
        print(f'{k}="{v}"')
PY
  fi
}

# Extract SecretString or SecretBinary from AWS response
extract_secret_payload() {
  if have_cmd jq; then
    jq -r 'if .SecretString then .SecretString
           elif .SecretBinary then .SecretBinary
           else empty end'
  else
    python3 - <<'PY'
import sys,json
j=json.load(sys.stdin)
if j.get('SecretString') is not None:
    print(j['SecretString'])
elif j.get('SecretBinary') is not None:
    print(j['SecretBinary'])
PY
  fi
}

looks_like_json_object() {
  case "$1" in
    \{*) return 0 ;;
    *)   return 1 ;;
  esac
}

# Turn backslash escapes (\n, \t, \x..) into real characters; strip CR
unescape_backslashes() {
  # Use printf %b which interprets backslash escapes; then remove \r
  # shellcheck disable=SC2059
  printf '%b' "$1" | tr -d '\r'
}

# Detect if text appears to be dotenv lines (at least one KEY=VALUE)
looks_like_dotenv() {
  printf '%s' "$1" | grep -Eq '^[A-Za-z_][A-Za-z0-9_]*='
}

# ---- credentials ----
if [ -z "${AWS_ACCESS_KEY_ID:-}" ] && [ -z "${PROFILE:-}" ]; then
  if [ -f ".aws.env" ]; then
    # shellcheck disable=SC1091
    . ./.aws.env
    log "Loaded AWS creds from ./.aws.env"
  fi
fi

have_cmd aws || die "aws CLI not found."

AWS_ARGS="--region $REGION"
if [ -z "${AWS_ACCESS_KEY_ID:-}" ] && [ -n "${PROFILE:-}" ]; then
  AWS_ARGS="$AWS_ARGS --profile $PROFILE"
fi

# ---- assemble fresh .env ----
tmp_env="$(mktemp)"
trap 'rm -f "$tmp_env"' EXIT

{
  echo "# Auto-generated by scripts/load-all-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "# Region: $REGION"
  echo
} > "$tmp_env"

for SECRET_ID in $DEFAULT_SECRETS; do
  log "Fetching secret: $SECRET_ID"
  if ! out="$(aws secretsmanager get-secret-value --secret-id "$SECRET_ID" $AWS_ARGS 2>/dev/null)"; then
    die "Failed to fetch $SECRET_ID (check name, region, credentials)"
  fi

  raw_payload="$(printf '%s' "$out" | extract_secret_payload)"
  [ -n "$raw_payload" ] || die "Secret $SECRET_ID payload empty"

  # Try base64-decode if it looks like binary; ignore errors
  payload="$raw_payload"
  if ! looks_like_json_object "$payload"; then
    if printf '%s' "$payload" | base64 -d >/dev/null 2>&1; then
      payload="$(printf '%s' "$payload" | base64 -d || printf '%s' "$payload")"
    fi
  fi

  # Convert \n sequences into real newlines and strip CR
  payload="$(unescape_backslashes "$payload")"

  if looks_like_json_object "$payload"; then
    lines="$(printf '%s' "$payload" | json_to_env_lines || printf '')"
    [ -n "$lines" ] || die "Secret $SECRET_ID parsed to no key/values (ensure flat JSON)"
    {
      echo "# From secret: $SECRET_ID (json)"
      printf '%s\n\n' "$lines"
    } >> "$tmp_env"
  elif looks_like_dotenv "$payload"; then
    {
      echo "# From secret: $SECRET_ID (dotenv)"
      # Normalize: remove blank lines and comments-only lines, then quote values
      printf '%s\n' "$payload" | awk 'NF && $0 !~ /^[[:space:]]*#/ {
        if (match($0, /^([^=]+)=(.*)$/, arr)) {
          key = arr[1]
          val = arr[2]
          # Remove existing quotes if present
          gsub(/^["'\'']|["'\'']$/, "", val)
          print key "=\"" val "\""
        } else {
          print
        }
      }'
      echo
    } >> "$tmp_env"
  else
    key="$(printf '%s' "$SECRET_ID" | tr ' ' '_' )"
    {
      echo "# From secret: $SECRET_ID (scalar)"
      echo "${key}=\"${payload}\""
      echo
    } >> "$tmp_env"
  fi
done

# ---- rewrite .env ----
mv "$tmp_env" .env
chmod 600 .env || true
log "Wrote fresh .env."
