from ..extensions import db
from .agent import AgentConnectionRequest, AgentConnections, ChatHistory, Todo
from .calendar import CalendarEvent, CalendarShare
from .documents import (
    Agreement,
    AgreementEvent,
    AgreementLink,
    AgreementParticipant,
    AgreementRevision,
    ChecklistForm,
    Document,
    DocumentLibraryItem,
    DocusignConnectEvent,
    DocusignOAuthToken,
    DocusignTemplate,
)
from .property import (
    HomeComment,
    HomeLikes,
    HomeNotInterested,
    HomeUniversal,
    PropertyAnalysisSection,
    PropertyCache,
    ReelLike,
    ScoringResultsTracker,
    Search,
    UserPropertyCommute,
    UserPropertyHighlights,
    UserPropertyLink,
    UserScoreWeights,
)
from .transactions import (
    ChecklistItemDispatchSetting,
    Transaction,
    TransactionAddress,
    TransactionTask,
)

# Import from organized subfolders for backward compatibility
from .user import (
    GoogleOAuthToken,
    OAuthState,
    User,
    UserAdmin,
    UserAgentProfile,
    UserCalendarConnection,
    UserCommunicationPrefs,
    UserDemographics,
    UserFinancials,
    UserImportantLocation,
    UserIntegration,
    UserIntentAttribute,
    UserRole,
    UserClientSettings,
    UserSearchDisplaySettings,
    UserSearchIntent,
)


# Initialize database
def init_db():
    db.create_all()


__all__ = [
    "User",
    "ChecklistItemDispatchSetting",
    "Transaction",
    "TransactionAddress",
    "TransactionTask",
    "Document",
    "DocumentLibraryItem",
    "ChecklistForm",
    "Agreement",
    "AgreementLink",
    "AgreementRevision",
    "AgreementParticipant",
    "AgreementEvent",
    "UserRole",
    "UserAdmin",
    "UserDemographics",
    "UserFinancials",
    "UserClientSettings",
    "UserSearchDisplaySettings",
    "UserSearchIntent",
    "UserIntentAttribute",
    "UserImportantLocation",
    "UserCommunicationPrefs",
    "UserCalendarConnection",
    "UserAgentProfile",
    "HomeComment",
    "HomeUniversal",
    "HomeLikes",
    "HomeNotInterested",
    "PropertyAnalysisSection",
    "PropertyCache",
    "ReelLike",
    "Search",
    "ScoringResultsTracker",
    "UserPropertyCommute",
    "UserPropertyHighlights",
    "UserPropertyLink",
    "UserScoreWeights",
    "AgentConnections",
    "AgentConnectionRequest",
    "ChatHistory",
    "Todo",
    "CalendarEvent",
    "CalendarShare",
    "GoogleOAuthToken",
    "OAuthState",
    "UserIntegration",
    "DocusignConnectEvent",
    "DocusignOAuthToken",
    "DocusignTemplate",
    "db",
]
