#!/usr/bin/env sh
# Split EXPO_PUBLIC_* keys from generated Server env files into Client/.env and Client/.env.example.
# Sourced by Server/scripts/secrets.sh — not intended for standalone use.

# Usage: split_client_public_env_from_server <server_env> <server_example> <client_dir> <region> <stamp>
split_client_public_env_from_server() {
  server_env="$1"
  server_example="$2"
  client_dir="$3"
  region="$4"
  stamp="$5"

  client_env_log() {
    if [ -n "${log:-}" ] && type log >/dev/null 2>&1; then
      log "$@"
    else
      printf '%s\n' "$*" >&2
    fi
  }

  _collect_expo_public_sorted() {
    env_file="$1"
    [ -f "$env_file" ] || return 0
    awk '/^EXPO_PUBLIC_[A-Za-z0-9_]*=/ {
      key = $0
      sub(/=.*/, "", key)
      lines[key] = $0
    }
    END {
      for (k in lines) print k "\t" lines[k]
    }' "$env_file" | sort -t "$(printf '\t')" -k1,1 | cut -f2-
  }

  _strip_expo_public_from_file() {
    file="$1"
    tmp_out="$(mktemp)"
    grep -Ev '^EXPO_PUBLIC_[A-Za-z0-9_]*=' "$file" >"$tmp_out" 2>/dev/null || : >"$tmp_out"
    mv "$tmp_out" "$file"
  }

  tmp_values="$(mktemp)"
  tmp_keys="$(mktemp)"
  tmp_client_env="$(mktemp)"
  tmp_client_example="$(mktemp)"

  _collect_expo_public_sorted "$server_env" >"$tmp_values"
  _collect_expo_public_sorted "$server_example" | awk -F= '{ print $1 }' >"$tmp_keys"

  if [ ! -s "$tmp_values" ] && [ ! -s "$tmp_keys" ]; then
    client_env_log "No EXPO_PUBLIC_* keys in fetched secrets; writing empty Client/.env and Client/.env.example"
  fi

  {
    echo "# Auto-generated by Server/scripts/secrets.sh on $stamp"
    echo "# Region: $region"
    echo "# Client bundle keys (Vite web / Expo mobile) — not used by Flask"
    echo
    if [ -s "$tmp_values" ]; then
      cat "$tmp_values"
    fi
    printf '\n'
  } >"$tmp_client_env"

  {
    echo "# Regenerated by Server/scripts/secrets.sh on $stamp (placeholder values only — run bash Server/scripts/secrets.sh for real credentials)"
    echo "# Region: $region"
    echo
    if [ -s "$tmp_values" ]; then
      while IFS= read -r line; do
        [ -z "$line" ] && continue
        key="${line%%=*}"
        printf '%s\n' "${key}=\"\""
      done <"$tmp_values"
    elif [ -s "$tmp_keys" ]; then
      while IFS= read -r key; do
        [ -z "$key" ] && continue
        printf '%s\n' "${key}=\"\""
      done <"$tmp_keys"
    fi
    printf '\n'
  } >"$tmp_client_example"

  mkdir -p "$client_dir"
  mv "$tmp_client_env" "$client_dir/.env"
  mv "$tmp_client_example" "$client_dir/.env.example"
  chmod 600 "$client_dir/.env" 2>/dev/null || true
  chmod 644 "$client_dir/.env.example" 2>/dev/null || true

  _strip_expo_public_from_file "$server_env"
  _strip_expo_public_from_file "$server_example"

  key_count="$(grep -Ec '^EXPO_PUBLIC_[A-Za-z0-9_]*=' "$client_dir/.env" 2>/dev/null || echo 0)"
  client_env_log "Wrote Client/.env and Client/.env.example ($key_count EXPO_PUBLIC_* key(s))."

  rm -f "$tmp_values" "$tmp_keys" "$tmp_client_env" "$tmp_client_example"
}
