import os

from ._constants_aws import S3_BUCKET_NAME_PDFS, S3_PRESIGNED_URL_EXPIRATION_DEFAULT

# AWS Cognito Settings
AWS_REGION = os.getenv("AWS_REGION", "us-east-2")
AWS_COGNITO_USER_POOL_ID = os.getenv("AWS_COGNITO_USER_POOL_ID")
AWS_COGNITO_CLIENT_ID = os.getenv("AWS_COGNITO_CLIENT_ID")
AWS_COGNITO_CLIENT_SECRET = os.getenv("AWS_COGNITO_CLIENT_SECRET")

# AWS S3 Settings
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")

S3_PRESIGNED_URL_EXPIRATION = int(
    os.getenv("S3_PRESIGNED_URL_EXPIRATION", S3_PRESIGNED_URL_EXPIRATION_DEFAULT)
)  # 1 hour default

__all__ = [
    "AWS_REGION",
    "AWS_COGNITO_USER_POOL_ID",
    "AWS_COGNITO_CLIENT_ID",
    "AWS_COGNITO_CLIENT_SECRET",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "S3_BUCKET_NAME_PDFS",
    "S3_PRESIGNED_URL_EXPIRATION",
]

