/** Ordered report sections for property analysis / compare (shared across profile onboarding and property details). */
export const DEFAULT_REPORT_SECTIONS = [
  {
    id: "demographics",
    key: "demographics",
    label: "Demographics",
    priority: 1,
    description: "Age, race, income, and education distribution",
    question: "What are the demographic characteristics of this area?",
  },
  {
    id: "affordability",
    key: "affordability",
    label: "Affordability",
    priority: 2,
    description: "Affordability, taxes, long-term costs, projected value",
    question: "Can I comfortably afford to live here now and long term?",
  },
  {
    id: "neighborhood",
    key: "neighborhood",
    label: "Neighborhood",
    priority: 3,
    description: "Safety, upkeep, community feel",
    question: "Is the area safe, pleasant, and stable?",
  },
  {
    id: "commute",
    key: "commute",
    label: "Commute",
    priority: 4,
    description: "Driving time, public transit, road quality, infrastructure",
    question: "Is it easy and efficient to get around from here?",
  },
  {
    id: "family_friendly",
    key: "family_friendly",
    label: "Family-Friendly",
    priority: 5,
    description: "Schools, parks, healthcare, kid-friendly amenities",
    question: "Is this a good place to raise kids and meet family needs?",
  },
  {
    id: "entertainment",
    key: "entertainment",
    label: "Entertainment",
    priority: 6,
    description: "Restaurants, bars, gyms, activities, overall vibe",
    question: "Are there enjoyable things to do nearby?",
  },
  {
    id: "investment",
    key: "investment",
    label: "Investment",
    priority: 7,
    description: "Future growth, job market stability, resale potential",
    question: "Is this area likely to appreciate or decline?",
  },
  {
    id: "climate_environmental_safety",
    key: "climate_environmental_safety",
    label: "Weather & Natural Risk",
    priority: 8,
    description: "Climate preference, flood/fire/hurricane risk",
    question: "Is the weather right for me, and is the area safe?",
  },
  {
    id: "convenience_walkability",
    key: "convenience_walkability",
    label: "Convenience & Walkability",
    priority: 9,
    description: "Grocery, daily services, walkability, errands without a car",
    question: "Is daily life here convenient and easy?",
  },
];
