"""migrate

Revision ID: 07fc3df465df
Revises: a1c2d3e4f5a6
Create Date: 2026-04-01 20:21:08.943338

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "07fc3df465df"
down_revision = "a1c2d3e4f5a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agreements", schema=None) as batch_op:
        batch_op.add_column(sa.Column("library_item_id", sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ["library_item_id"])
        batch_op.create_foreign_key(None, "document_library_items", ["library_item_id"], ["id"])

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("library_item_id", sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ["library_item_id"])
        batch_op.create_foreign_key(None, "document_library_items", ["library_item_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("library_item_id")

    with op.batch_alter_table("agreements", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("library_item_id")

    # ### end Alembic commands ###
