"""migrate

Revision ID: 08a5c7383208
Revises: c3eb1c7805e4
Create Date: 2025-11-09 16:22:55.944253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08a5c7383208'
down_revision = 'c3eb1c7805e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_descriptions')
    op.drop_table('subscriptions')
    # Add column as nullable first with server default for existing rows
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closing_mode', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    
    # Update any existing NULL values (shouldn't be any, but safety first)
    op.execute("UPDATE users SET is_closing_mode = false WHERE is_closing_mode IS NULL")
    
    # Now make the column NOT NULL and remove server default
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_closing_mode', nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_closing_mode')

    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('current_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('canceled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reports_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reports_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    op.create_table('home_descriptions',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('home_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('positives', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('negatives', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'home_id', name=op.f('home_descriptions_pkey'))
    )
    # ### end Alembic commands ###
