"""Update User model

Revision ID: 0ced8a1faabe
Revises: 8f31008455ab
Create Date: 2025-07-07 17:32:05.466684

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0ced8a1faabe"
down_revision = "8f31008455ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reports_available", sa.Integer(), nullable=True))
        batch_op.drop_column("agency_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("agency_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("reports_available")

    # ### end Alembic commands ###
