"""migrate

Revision ID: 0fffb22ab6b3
Revises: 08a5c7383208
Create Date: 2025-12-18 15:50:43.464495

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0fffb22ab6b3"
down_revision = "08a5c7383208"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plaid_asset_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plaid_asset_reports_asset_report_token"))
        batch_op.drop_index(batch_op.f("ix_plaid_asset_reports_user_id"))

    op.drop_table("plaid_asset_reports")
    with op.batch_alter_table("plaid_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plaid_items_item_id"))
        batch_op.drop_index(batch_op.f("ix_plaid_items_user_id"))

    op.drop_table("plaid_items")
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("conversation_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("sender_id", sa.String(length=36), nullable=True))
        batch_op.alter_column("report_id", existing_type=sa.VARCHAR(length=255), nullable=True)
        batch_op.create_foreign_key(None, "agent_conversations", ["conversation_id"], ["id"])

    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        batch_op.drop_column("zillow_url")

    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_column("solo_reports_created")
        batch_op.drop_column("group_reports_created")
        batch_op.drop_column("solo_reports_addresses")
        batch_op.drop_column("group_reports_addresses")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("group_reports_addresses", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("solo_reports_addresses", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("group_reports_created", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("solo_reports_created", sa.INTEGER(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("zillow_url", sa.VARCHAR(length=1024), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("report_id", existing_type=sa.VARCHAR(length=255), nullable=False)
        batch_op.drop_column("sender_id")
        batch_op.drop_column("conversation_id")

    op.create_table(
        "plaid_items",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('plaid_items_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("item_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("access_token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("institution_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("institution_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("linked_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("last_sync", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="plaid_items_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="plaid_items_pkey"),
        postgresql_ignore_search_path=False,
    )
    with op.batch_alter_table("plaid_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plaid_items_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_plaid_items_item_id"), ["item_id"], unique=True)

    op.create_table(
        "plaid_asset_reports",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("plaid_item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "asset_report_token", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("asset_report_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("days_requested", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["plaid_item_id"],
            ["plaid_items.id"],
            name=op.f("plaid_asset_reports_plaid_item_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("plaid_asset_reports_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("plaid_asset_reports_pkey")),
    )
    with op.batch_alter_table("plaid_asset_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plaid_asset_reports_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_plaid_asset_reports_asset_report_token"),
            ["asset_report_token"],
            unique=True,
        )

    # ### end Alembic commands ###
