"""Add is_agent field to User model

Revision ID: 13bb2089ef63
Revises: 1cc9c4bf4fa5
Create Date: 2025-07-26 17:11:24.355232

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13bb2089ef63"
down_revision = "1cc9c4bf4fa5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_agent", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_agent")

    # ### end Alembic commands ###
