"""Refactor to_dict for onboarding fields only

Revision ID: 15bf956a983a
Revises: a70241a07b68
Create Date: 2025-08-07 14:58:24.402871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bf956a983a'
down_revision = 'a70241a07b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('document_ids')

    # ### end Alembic commands ###
