"""migrate

Revision ID: 1af67d5f1f71
Revises: d322cd57307f
Create Date: 2026-01-15 21:21:26.926562

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1af67d5f1f71"
down_revision = "d322cd57307f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pdf_documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.Text(), nullable=True))
        batch_op.drop_column("primary_address")
        batch_op.drop_column("comparison_address")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pdf_documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("comparison_address", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("primary_address", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("address")

    # ### end Alembic commands ###
