"""migrate

Revision ID: 1c5f7158b4cb
Revises: c2d903acebb0
Create Date: 2026-02-17 20:01:15.368790

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c5f7158b4cb"
down_revision = "c2d903acebb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("why_joining_silverkey", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("must_have", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("listing_type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("preferred_sqft_min", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("preferred_sqft_max", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("days_on_market_max", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("preferred_lot_size_min", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("preferred_lot_size_max", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("preferred_home_age_max", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_column("preferred_home_age_max")
        batch_op.drop_column("preferred_lot_size_max")
        batch_op.drop_column("preferred_lot_size_min")
        batch_op.drop_column("days_on_market_max")
        batch_op.drop_column("preferred_sqft_max")
        batch_op.drop_column("preferred_sqft_min")
        batch_op.drop_column("listing_type")
        batch_op.drop_column("must_have")
        batch_op.drop_column("why_joining_silverkey")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
