"""Remove individual include_* boolean fields, keep only report_section_priorities

Revision ID: 1cc9c4bf4fa5
Revises: b512ecfb8281
Create Date: 2025-07-26 16:15:46.115393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc9c4bf4fa5'
down_revision = 'b512ecfb8281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('include_environment')
        batch_op.drop_column('include_safety')
        batch_op.drop_column('include_commute')
        batch_op.drop_column('include_schools')
        batch_op.drop_column('include_nightlife_and_dating')
        batch_op.drop_column('include_extra_tips')
        batch_op.drop_column('include_neighborhood_overview')
        batch_op.drop_column('include_local_amenities')
        batch_op.drop_column('include_accessibility')
        batch_op.drop_column('include_development')
        batch_op.drop_column('include_culture_and_events')
        batch_op.drop_column('include_family_friendly')
        batch_op.drop_column('include_weather')
        batch_op.drop_column('include_social_character')
        batch_op.drop_column('include_money')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_money', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_social_character', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_weather', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_family_friendly', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_culture_and_events', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_development', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_accessibility', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_local_amenities', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_neighborhood_overview', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_extra_tips', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_nightlife_and_dating', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_schools', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_commute', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_safety', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('include_environment', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
