"""migrate

Revision ID: 23d22005c175
Revises: b4e05db7e151
Create Date: 2026-02-17 21:05:01.728063

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "23d22005c175"
down_revision = "b4e05db7e151"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profile")
    op.drop_table("user_events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("preferences_version", sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("preferences_version")

    op.create_table(
        "user_events",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "payload", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_events_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("user_events_pkey")),
    )
    op.create_table(
        "user_profile",
        sa.Column("user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("profile_version", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_profile_user_id_fkey")),
        sa.PrimaryKeyConstraint("user_id", name=op.f("user_profile_pkey")),
    )
    # ### end Alembic commands ###
