"""migrate

Revision ID: 2ca9d9ff4cfb
Revises: 7429ded55439
Create Date: 2025-10-29 19:19:07.180602

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ca9d9ff4cfb"
down_revision = "7429ded55439"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        # Add with server default so existing rows get a non-null value
        batch_op.add_column(
            sa.Column("is_liked", sa.Boolean(), nullable=True, server_default=sa.text("false"))
        )
        # Ensure all existing rows are populated (safety for databases that may ignore server_default on existing rows)
        batch_op.alter_column("is_liked", existing_type=sa.Boolean(), nullable=False)
        # Drop server default to avoid unintended defaults on future inserts from DB side
        batch_op.alter_column("is_liked", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        batch_op.drop_column("is_liked")

    # ### end Alembic commands ###
