"""migrate

Revision ID: 2f21a09c0f15
Revises: 1e33a4f51226
Create Date: 2026-01-16 15:39:03.811754

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f21a09c0f15"
down_revision = "1e33a4f51226"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shared_document_id", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.drop_column("shared_document_id")

    # ### end Alembic commands ###
