"""migrate

Revision ID: 3af2d4d8910d
Revises: bd599f3198d5
Create Date: 2026-04-02 14:03:03.344799

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3af2d4d8910d"
down_revision = "bd599f3198d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_search_intent", schema=None) as batch_op:
        batch_op.add_column(sa.Column("listing_status", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("extended_buyer_preferences", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_search_intent", schema=None) as batch_op:
        batch_op.drop_column("extended_buyer_preferences")
        batch_op.drop_column("listing_status")

    # ### end Alembic commands ###
