"""Add missing user preference fields

Revision ID: 4054dd28ff69
Revises: d0f8c38966a9
Create Date: 2025-07-25 11:19:39.797815

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4054dd28ff69"
down_revision = "d0f8c38966a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("communication_preference", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("meeting_availability", sa.String(length=20), nullable=True))
        batch_op.add_column(
            sa.Column("response_time_expectation", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("additional_context", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_column("additional_context")
        batch_op.drop_column("response_time_expectation")
        batch_op.drop_column("meeting_availability")
        batch_op.drop_column("communication_preference")

    # ### end Alembic commands ###
