"""migrate

Revision ID: 49f1e1fd6f5d
Revises: 3af2d4d8910d
Create Date: 2026-04-06 16:41:47.679850

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "49f1e1fd6f5d"
down_revision = "3af2d4d8910d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_connection_requests", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("agent_conversations", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("agreement_events", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("agreement_revisions", schema=None) as batch_op:
        batch_op.alter_column("mime_type", existing_type=sa.VARCHAR(length=100), nullable=False)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("agreements", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.alter_column("timezone", existing_type=sa.VARCHAR(length=100), nullable=False)
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.alter_column("is_synced", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("sync_source", existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("calendar_shares", schema=None) as batch_op:
        batch_op.alter_column("role", existing_type=sa.VARCHAR(length=20), nullable=False)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.alter_column("timestamp", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("document_library_items", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=20), nullable=False)
        batch_op.alter_column("document_type", existing_type=sa.VARCHAR(length=20), nullable=False)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("docusign_connect_events", schema=None) as batch_op:
        batch_op.alter_column("processed", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("hmac_verified", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("received_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("docusign_oauth_tokens", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("docusign_templates", schema=None) as batch_op:
        batch_op.alter_column("synced_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table("home_comments", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("home_likes", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("home_not_interested", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("reel_likes", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("transaction_addresses", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("user_agent_profiles", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("user_calendar_connections", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("user_google_tokens", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("user_integrations", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("user_tasks", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("user_tasks", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("user_integrations", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("user_google_tokens", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("user_calendar_connections", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("user_agent_profiles", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("transaction_addresses", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("reel_likes", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("home_not_interested", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("home_likes", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("home_comments", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("docusign_templates", schema=None) as batch_op:
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("synced_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("docusign_oauth_tokens", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("docusign_connect_events", schema=None) as batch_op:
        batch_op.alter_column("received_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("hmac_verified", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("processed", existing_type=sa.BOOLEAN(), nullable=True)

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("document_type", existing_type=sa.VARCHAR(length=20), nullable=True)
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=20), nullable=True)

    with op.batch_alter_table("document_library_items", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.alter_column("timestamp", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("calendar_shares", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("role", existing_type=sa.VARCHAR(length=20), nullable=True)

    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("sync_source", existing_type=sa.VARCHAR(length=50), nullable=True)
        batch_op.alter_column("is_synced", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=50), nullable=True)
        batch_op.alter_column("timezone", existing_type=sa.VARCHAR(length=100), nullable=True)

    with op.batch_alter_table("agreements", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("agreement_revisions", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("mime_type", existing_type=sa.VARCHAR(length=100), nullable=True)

    with op.batch_alter_table("agreement_events", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("agent_conversations", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    with op.batch_alter_table("agent_connection_requests", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)

    # ### end Alembic commands ###
