"""migrate

Revision ID: 4bcf075d61f8
Revises: 23d22005c175
Create Date: 2026-02-18 00:11:48.870309

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4bcf075d61f8"
down_revision = "23d22005c175"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_preferences")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("gender", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("occupation", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("credit_score_range", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("preferred_lot_size", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("preferred_home_age", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "preferred_architectural_style",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "walkability_importance", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("deal_breakers", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "communication_frequency", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "information_detail_level", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("data_sources", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_updated_section", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("preferences_version", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("chat_sessions", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("preferred_bathrooms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("preferred_bedrooms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("preferred_home_features", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("important_locations", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("pets", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "gross_income", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "down_payment", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("ideal_zip_code", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column("housing_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "renovation_preference", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "architectural_style_preference",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("has_buyers_agent", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column("looking_for_buyers_agent", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "intended_property_use", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "home_budget_min", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "home_budget_max", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("disabled_calendars", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("preferred_bedrooms_min", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("preferred_bedrooms_max", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("preferred_bathrooms_min", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("preferred_bathrooms_max", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column("why_joining_silverkey", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("must_have", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("listing_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("preferred_sqft_min", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("preferred_sqft_max", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("days_on_market_max", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "preferred_lot_size_min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "preferred_lot_size_max",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("preferred_home_age_max", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_preferences_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_preferences_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("user_preferences_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
