"""Add important_locations field to user_preferences

Revision ID: 4d9e2babcd55
Revises: 9d17975ff506
Create Date: 2025-08-02 18:04:14.505494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9e2babcd55'
down_revision = '9d17975ff506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('important_locations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('important_locations')

    # ### end Alembic commands ###
