"""Remove commute_tolerance column and update important_locations structure

Revision ID: 5886c51cfe11
Revises: ed30cd95a326
Create Date: 2025-08-11 14:03:50.014204

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5886c51cfe11"
down_revision = "ed30cd95a326"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_column("commute_tolerance")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "commute_tolerance",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
