"""Add favorite_homes field to User model

Revision ID: 5b0877d133c5
Revises: 30359e4ac8ce
Create Date: 2025-08-15 10:06:11.437971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0877d133c5'
down_revision = '30359e4ac8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_universal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_id', sa.String(length=36), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_homes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_homes')

    with op.batch_alter_table('home_universal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.drop_column('home_id')

    # ### end Alembic commands ###
