"""migrate

Revision ID: 5bdb3e4ae894
Revises: b35aa5123429
Create Date: 2026-01-02 17:52:57.777438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdb3e4ae894'
down_revision = 'b35aa5123429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled_calendars', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('disabled_calendars')

    # ### end Alembic commands ###
