"""migrate

Revision ID: 7429ded55439
Revises: f9cbadcc8e55
Create Date: 2025-10-29 18:39:55.270334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7429ded55439'
down_revision = 'f9cbadcc8e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_descriptions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_descriptions',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('home_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('positives', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('negatives', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'home_id', name=op.f('home_descriptions_pkey'))
    )
    # ### end Alembic commands ###
