"""Add client_ids and agent_id fields to User model

Revision ID: 8460ff150cc7
Revises: 13bb2089ef63
Create Date: 2025-07-28 16:33:56.293276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8460ff150cc7'
down_revision = '13bb2089ef63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_ids', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('agent_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('agent_id')
        batch_op.drop_column('client_ids')

    # ### end Alembic commands ###
