"""Refactor to_dict for onboarding fields only

Revision ID: 84c86e3daa4e
Revises: aa07d0ae783f
Create Date: 2025-08-13 20:10:24.646658

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "84c86e3daa4e"
down_revision = "aa07d0ae783f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_column("preferred_regions")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("preferred_regions", sa.TEXT(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
