"""migrate

Revision ID: 863a510e8d8e
Revises: fdbdccfd0567
Create Date: 2026-03-11 01:02:24.607769

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "863a510e8d8e"
down_revision = "fdbdccfd0567"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("docusign_templates")
    with op.batch_alter_table("docusign_connect_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_envelope_event_time"))
        batch_op.drop_index(batch_op.f("ix_docusign_connect_events_envelope_id"))

    op.drop_table("docusign_connect_events")
    op.drop_table("docusign_oauth_tokens")
    op.drop_table("user_preferences")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("chat_sessions", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("preferences_version", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column(
            "last_updated_section", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("data_sources", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("gender", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("occupation", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("pets", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "gross_income", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "home_budget_min", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "home_budget_max", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("credit_score_range", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "down_payment", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("ideal_zip_code", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column("housing_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("preferred_bathrooms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("preferred_bedrooms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("preferred_lot_size", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("preferred_home_age", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "preferred_architectural_style",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "renovation_preference", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "architectural_style_preference",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "intended_property_use", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("preferred_home_features", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("deal_breakers", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("important_locations", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "walkability_importance", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "communication_frequency", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "information_detail_level", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("has_buyers_agent", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column("looking_for_buyers_agent", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("disabled_calendars", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_preferences_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_preferences_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("user_preferences_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "docusign_oauth_tokens",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("access_token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("refresh_token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("token_expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("base_uri", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("scopes", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("docusign_oauth_tokens_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("docusign_oauth_tokens_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("docusign_oauth_tokens_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "docusign_connect_events",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("envelope_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("event_timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("payload", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("processed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("processed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("processing_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("retry_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("hmac_verified", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("received_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("docusign_connect_events_pkey")),
    )
    with op.batch_alter_table("docusign_connect_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_docusign_connect_events_envelope_id"), ["envelope_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_envelope_event_time"),
            ["envelope_id", "event_type", "event_timestamp"],
            unique=True,
        )

    op.create_table(
        "docusign_templates",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "docusign_template_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("template_variables", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("category", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("synced_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("docusign_templates_pkey")),
        sa.UniqueConstraint(
            "docusign_template_id",
            name=op.f("docusign_templates_docusign_template_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
