"""Add user_preferences table

Revision ID: 8834d3625782
Revises: 0ced8a1faabe
Create Date: 2025-07-24 18:22:08.225827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8834d3625782'
down_revision = '0ced8a1faabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('children_ages', sa.Text(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('employment_status', sa.String(length=30), nullable=True),
    sa.Column('income_range', sa.String(length=30), nullable=True),
    sa.Column('credit_score_range', sa.String(length=20), nullable=True),
    sa.Column('debt_to_income_ratio', sa.Float(), nullable=True),
    sa.Column('savings_amount_range', sa.String(length=30), nullable=True),
    sa.Column('investment_experience', sa.String(length=20), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('financial_goals', sa.Text(), nullable=True),
    sa.Column('current_housing_type', sa.String(length=30), nullable=True),
    sa.Column('current_housing_status', sa.String(length=20), nullable=True),
    sa.Column('desired_housing_type', sa.String(length=30), nullable=True),
    sa.Column('preferred_property_size', sa.String(length=20), nullable=True),
    sa.Column('preferred_lot_size', sa.String(length=20), nullable=True),
    sa.Column('preferred_home_age', sa.String(length=20), nullable=True),
    sa.Column('preferred_architectural_style', sa.String(length=50), nullable=True),
    sa.Column('preferred_regions', sa.Text(), nullable=True),
    sa.Column('preferred_climate', sa.String(length=30), nullable=True),
    sa.Column('urban_rural_preference', sa.String(length=20), nullable=True),
    sa.Column('commute_tolerance', sa.Integer(), nullable=True),
    sa.Column('proximity_to_family', sa.String(length=20), nullable=True),
    sa.Column('walkability_importance', sa.String(length=20), nullable=True),
    sa.Column('lifestyle_type', sa.String(length=30), nullable=True),
    sa.Column('hobbies_interests', sa.Text(), nullable=True),
    sa.Column('travel_frequency', sa.String(length=20), nullable=True),
    sa.Column('dining_preferences', sa.Text(), nullable=True),
    sa.Column('shopping_preferences', sa.Text(), nullable=True),
    sa.Column('entertainment_preferences', sa.Text(), nullable=True),
    sa.Column('fitness_activities', sa.Text(), nullable=True),
    sa.Column('tech_savviness', sa.String(length=20), nullable=True),
    sa.Column('preferred_communication', sa.String(length=20), nullable=True),
    sa.Column('social_media_usage', sa.String(length=20), nullable=True),
    sa.Column('online_shopping_frequency', sa.String(length=20), nullable=True),
    sa.Column('device_preferences', sa.Text(), nullable=True),
    sa.Column('decision_making_style', sa.String(length=30), nullable=True),
    sa.Column('research_behavior', sa.String(length=30), nullable=True),
    sa.Column('brand_loyalty', sa.String(length=20), nullable=True),
    sa.Column('price_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('early_adopter_tendency', sa.String(length=20), nullable=True),
    sa.Column('impulse_buying_tendency', sa.String(length=20), nullable=True),
    sa.Column('health_consciousness', sa.String(length=20), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('exercise_frequency', sa.String(length=20), nullable=True),
    sa.Column('stress_level', sa.String(length=20), nullable=True),
    sa.Column('sleep_schedule', sa.String(length=20), nullable=True),
    sa.Column('environmental_consciousness', sa.String(length=20), nullable=True),
    sa.Column('sustainability_importance', sa.String(length=20), nullable=True),
    sa.Column('social_causes_supported', sa.Text(), nullable=True),
    sa.Column('political_leaning', sa.String(length=20), nullable=True),
    sa.Column('community_involvement', sa.String(length=20), nullable=True),
    sa.Column('preferred_support_channel', sa.String(length=20), nullable=True),
    sa.Column('service_expectations', sa.String(length=20), nullable=True),
    sa.Column('complaint_behavior', sa.String(length=30), nullable=True),
    sa.Column('loyalty_program_participation', sa.String(length=20), nullable=True),
    sa.Column('privacy_concern_level', sa.String(length=20), nullable=True),
    sa.Column('data_sharing_comfort', sa.String(length=20), nullable=True),
    sa.Column('security_awareness', sa.String(length=20), nullable=True),
    sa.Column('property_search_stage', sa.String(length=30), nullable=True),
    sa.Column('home_buying_experience', sa.String(length=20), nullable=True),
    sa.Column('financing_preference', sa.String(length=30), nullable=True),
    sa.Column('property_features_priority', sa.Text(), nullable=True),
    sa.Column('deal_breakers', sa.Text(), nullable=True),
    sa.Column('renovation_willingness', sa.String(length=20), nullable=True),
    sa.Column('communication_frequency', sa.String(length=20), nullable=True),
    sa.Column('information_detail_level', sa.String(length=20), nullable=True),
    sa.Column('meeting_preference', sa.String(length=20), nullable=True),
    sa.Column('response_time_expectation', sa.String(length=20), nullable=True),
    sa.Column('follow_up_preference', sa.String(length=20), nullable=True),
    sa.Column('data_sources', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_updated_section', sa.String(length=50), nullable=True),
    sa.Column('preferences_version', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
