"""migrate

Revision ID: 92c1d13e5453
Revises: 2ca9d9ff4cfb
Create Date: 2025-10-29 19:30:46.866916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c1d13e5453'
down_revision = '2ca9d9ff4cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_universal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('zipcode', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('image_urls', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('zpid', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('listing_status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('property_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('home_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('year_built', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('living_area', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lot_area_value', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lot_area_unit', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('property_analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('commute_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('zillow_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('raw_data', sa.JSON(), nullable=True))
        batch_op.alter_column('is_liked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_universal', schema=None) as batch_op:
        batch_op.alter_column('is_liked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_column('raw_data')
        batch_op.drop_column('zillow_url')
        batch_op.drop_column('commute_data')
        batch_op.drop_column('property_analysis')
        batch_op.drop_column('features')
        batch_op.drop_column('lot_area_unit')
        batch_op.drop_column('lot_area_value')
        batch_op.drop_column('living_area')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('year_built')
        batch_op.drop_column('home_type')
        batch_op.drop_column('property_type')
        batch_op.drop_column('listing_status')
        batch_op.drop_column('zpid')
        batch_op.drop_column('image_urls')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
