"""migrate

Revision ID: 94787aa5ba65
Revises: a8f3c2e1d0b4
Create Date: 2026-04-10 13:01:54.214860

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "94787aa5ba65"
down_revision = "a8f3c2e1d0b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_search_display", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_search_context",
                postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_search_display", schema=None) as batch_op:
        batch_op.drop_column("last_search_context")

    # ### end Alembic commands ###
