"""Change agent_id from String to Text to support multiple agents

Revision ID: 9d17975ff506
Revises: 8460ff150cc7
Create Date: 2025-07-28 22:29:36.691505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d17975ff506'
down_revision = '8460ff150cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('agent_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('agent_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###
