"""migrate

Revision ID: a02ed1527a24
Revises: d7ff5b8c2ce5
Create Date: 2026-01-02 18:38:54.623848

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a02ed1527a24"
down_revision = "d7ff5b8c2ce5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("milestones")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "milestones",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("property_address", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("scheduled_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("duration_minutes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("google_event_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("google_calendar_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("google_event_link", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("milestones_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("milestones_pkey")),
    )
    # ### end Alembic commands ###
