"""migrate

Revision ID: a0a768474b70
Revises: f4b9d44a2744
Create Date: 2026-01-06 12:07:21.978097

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a0a768474b70"
down_revision = "f4b9d44a2744"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("home_likes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mls_home_id", sa.String(length=64), nullable=True))
        batch_op.drop_column("living_area")
        batch_op.drop_column("home_type")
        batch_op.drop_column("year_built")
        batch_op.drop_column("price")
        batch_op.drop_column("image_url")
        batch_op.drop_column("property_type")
        batch_op.drop_column("lot_size")
        batch_op.drop_column("lot_area_unit")
        batch_op.drop_column("state")
        batch_op.drop_column("sqft")
        batch_op.drop_column("features")
        batch_op.drop_column("city")
        batch_op.drop_column("commute_data")
        batch_op.drop_column("image_urls")
        batch_op.drop_column("property_analysis")
        batch_op.drop_column("zipcode")
        batch_op.drop_column("lot_area_value")
        batch_op.drop_column("baths")
        batch_op.drop_column("listing_status")
        batch_op.drop_column("beds")
        batch_op.drop_column("raw_data")

    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mls_home_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("mls_agent_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("listing_agent_phone", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("listing_agent_email", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("brokerage", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("mls_region", sa.String(length=64), nullable=True))

    with op.batch_alter_table("search_session", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mls_home_id", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_session", schema=None) as batch_op:
        batch_op.drop_column("mls_home_id")

    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        batch_op.drop_column("mls_region")
        batch_op.drop_column("brokerage")
        batch_op.drop_column("listing_agent_email")
        batch_op.drop_column("listing_agent_phone")
        batch_op.drop_column("mls_agent_id")
        batch_op.drop_column("mls_home_id")

    with op.batch_alter_table("home_likes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "raw_data",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("beds", sa.VARCHAR(length=36), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("listing_status", sa.VARCHAR(length=64), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("baths", sa.VARCHAR(length=36), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("lot_area_value", sa.VARCHAR(length=36), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("zipcode", sa.VARCHAR(length=32), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "property_analysis",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "image_urls",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "commute_data",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("city", sa.VARCHAR(length=120), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "features",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("sqft", sa.VARCHAR(length=36), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("state", sa.VARCHAR(length=64), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("lot_area_unit", sa.VARCHAR(length=32), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("lot_size", sa.VARCHAR(length=36), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("property_type", sa.VARCHAR(length=64), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("image_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("price", sa.VARCHAR(length=36), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("year_built", sa.VARCHAR(length=16), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("home_type", sa.VARCHAR(length=64), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("living_area", sa.VARCHAR(length=36), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("mls_home_id")

    # ### end Alembic commands ###
