"""migrate

Revision ID: a3379a2da9b3
Revises: 863a510e8d8e
Create Date: 2026-03-16 10:46:46.962079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3379a2da9b3'
down_revision = '863a510e8d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_agent_profile')
    with op.batch_alter_table('agreement_links', schema=None) as batch_op:
        batch_op.alter_column('linked_item_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_agreement_links_agreement_id'), ['agreement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agreement_links_transaction_id'), ['transaction_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('agreement_links_agreement_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'agreements', ['agreement_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('skyslope_form_id')

    with op.batch_alter_table('transaction_addresses', schema=None) as batch_op:
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('place_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_transaction_addresses_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('skyslope_file_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('property_address_id')

    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_integration_provider'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_integrations_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_integrations_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_provider', ['user_id', 'provider'])
        batch_op.drop_constraint(batch_op.f('user_integrations_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_integrations_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_user_provider', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_integrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_integrations_provider'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_integration_provider'), ['user_id', 'provider'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_address_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('skyslope_file_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('transaction_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_addresses_user_id'))
        batch_op.alter_column('place_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('street',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skyslope_form_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))

    with op.batch_alter_table('agreement_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('agreement_links_agreement_id_fkey'), 'agreements', ['agreement_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_agreement_links_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_agreement_links_agreement_id'))
        batch_op.alter_column('linked_item_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    op.create_table('user_agent_profile',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('physical_mailing_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('licensed_states', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('license_types', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('license_numbers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('license_expiration_dates', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mls_affiliations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brokerage_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('brokerage_bic_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('brokerage_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('brokerage_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('brokerage_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('professional_headshot_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('agent_bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_service_zips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specialties', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('social_links', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_agent_profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_agent_profile_pkey'))
    )
    # ### end Alembic commands ###
