"""Refactor to_dict for onboarding fields only

Revision ID: a4ccf2932271
Revises: 5886c51cfe11
Create Date: 2025-08-12 22:09:55.453714

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a4ccf2932271"
down_revision = "5886c51cfe11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("document_ids")
        batch_op.drop_column("favorite_home_ids")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("favorite_home_ids", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("document_ids", sa.TEXT(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
