"""Refactor to_dict for onboarding fields only

Revision ID: aa07d0ae783f
Revises: a4ccf2932271
Create Date: 2025-08-12 22:25:53.886035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa07d0ae783f'
down_revision = 'a4ccf2932271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_universal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_universal', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
