"""Add google_id and make cognito_id nullable for OAuth users

Revision ID: i8j9k0l1m2n3
Revises: h3a4b5c6d7e8
Create Date: 2025-10-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'i8j9k0l1m2n3'
down_revision = 'h3a4b5c6d7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add google_id column
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])
        
        # Make cognito_id nullable to support Google OAuth users
        batch_op.alter_column('cognito_id',
                              existing_type=sa.String(length=36),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Revert cognito_id to non-nullable (this may fail if there are Google OAuth users)
        batch_op.alter_column('cognito_id',
                              existing_type=sa.String(length=36),
                              nullable=False)
        
        # Drop google_id column
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###

