"""Add google_id and make cognito_id nullable for OAuth users

Revision ID: f1a2b3c4d5e6
Revises: 13bb2089ef63
Create Date: 2025-10-15 12:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1a2b3c4d5e6"
down_revision = "13bb2089ef63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        # Add google_id column
        batch_op.add_column(sa.Column("google_id", sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint("uq_users_google_id", ["google_id"])

        # Make cognito_id nullable to support Google OAuth users
        batch_op.alter_column("cognito_id", existing_type=sa.String(length=36), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        # Revert cognito_id to non-nullable (this may fail if there are Google OAuth users)
        batch_op.alter_column("cognito_id", existing_type=sa.String(length=36), nullable=False)

        # Drop google_id column
        batch_op.drop_constraint("uq_users_google_id", type_="unique")
        batch_op.drop_column("google_id")

    # ### end Alembic commands ###
