"""Add home budget range fields

Revision ID: f1a2b3c4d5e6
Revises: f9da91fb8590
Create Date: 2025-10-13 12:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# AFTER
revision = "b7c8d9e0f1a2"  # <-- NEW id (pick your own 12-hex if you prefer)
down_revision = "f9da91fb8590"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("home_budget_min", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("home_budget_max", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_column("home_budget_max")
        batch_op.drop_column("home_budget_min")

    # ### end Alembic commands ###
