"""migrate

Revision ID: b35aa5123429
Revises: a76b7de633cb
Create Date: 2025-12-26 12:49:57.943331

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b35aa5123429"
down_revision = "a76b7de633cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shared_home_id", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.drop_column("shared_home_id")

    # ### end Alembic commands ###
