"""empty message

Revision ID: b3c6574a3b7e
Revises: 6a953654ed77
Create Date: 2025-08-07 10:51:25.625662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c6574a3b7e'
down_revision = '6a953654ed77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspections_checklist', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('closing_checklist', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timeline_checklist', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('financing_checklist', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('escrow_checklist', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('escrow_checklist')
        batch_op.drop_column('financing_checklist')
        batch_op.drop_column('timeline_checklist')
        batch_op.drop_column('closing_checklist')
        batch_op.drop_column('inspections_checklist')

    # ### end Alembic commands ###
