"""migrate

Revision ID: b4e05db7e151
Revises: 1c5f7158b4cb
Create Date: 2026-02-17 20:17:17.081345

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4e05db7e151"
down_revision = "1c5f7158b4cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agreements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agreements_current_revision_id"))
        batch_op.drop_constraint(
            batch_op.f("agreements_current_revision_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("current_revision_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agreements", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "current_revision_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("agreements_current_revision_id_fkey"),
            "agreement_revisions",
            ["current_revision_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_index(
            batch_op.f("ix_agreements_current_revision_id"), ["current_revision_id"], unique=False
        )

    # ### end Alembic commands ###
