"""Add report details to pdf_documents

Revision ID: b512ecfb8281
Revises: b67fd3e9b791
Create Date: 2025-07-26 10:27:09.486019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b512ecfb8281'
down_revision = 'b67fd3e9b791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comparison_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('report_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_documents', schema=None) as batch_op:
        batch_op.drop_column('report_type')
        batch_op.drop_column('comparison_address')
        batch_op.drop_column('primary_address')

    # ### end Alembic commands ###
