"""Increase chat_history report_id field length to 255 characters

Revision ID: b59fd3e8a725
Revises: d9631abfec2a
Create Date: 2025-08-05 20:49:49.118667

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b59fd3e8a725"
down_revision = "d9631abfec2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.alter_column(
            "report_id",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.alter_column(
            "report_id",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
