"""Add report_section_priorities field to user_preferences

Revision ID: b67fd3e9b791
Revises: dbe77c1ab14f
Create Date: 2025-07-25 14:35:04.890533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67fd3e9b791'
down_revision = 'dbe77c1ab14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_section_priorities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('report_section_priorities')

    # ### end Alembic commands ###
