"""Refactor to_dict for onboarding fields only

Revision ID: b85887b0e6e5
Revises: 5b0877d133c5
Create Date: 2025-08-15 14:35:52.763016
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b85887b0e6e5'
down_revision = '5b0877d133c5'
branch_labels = None
depends_on = None

# Use a neutral placeholder that won't collide with real user IDs.
_DEFAULT_USER_ID = '00000000-0000-0000-0000-000000000000'


def upgrade():
    # ### commands auto generated by Alembic - adjusted to avoid NOT NULL violation ###
    with op.batch_alter_table('home_descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('positives', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('negatives', sa.String(length=500), nullable=True))
        batch_op.drop_column('property_analysis')

    # We add user_id with a temporary server default so existing rows get populated,
    # then drop the default and set NOT NULL.
    with op.batch_alter_table('home_universal', schema=None) as batch_op:
        # 1) Add as NULLABLE with DEFAULT to backfill existing rows
        batch_op.add_column(
            sa.Column('user_id', sa.String(length=36), nullable=True, server_default=_DEFAULT_USER_ID)
        )
        batch_op.add_column(sa.Column('beds', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('baths', sa.String(length=36), nullable=True))
        batch_op.alter_column(
            'sqft',
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=True
        )
        batch_op.drop_column('days_on_zillow')
        batch_op.drop_column('bathrooms_full')
        batch_op.drop_column('lng')
        batch_op.drop_column('virtual_tour')
        batch_op.drop_column('has_association')
        batch_op.drop_column('parcel_number')
        batch_op.drop_column('page_view_count')
        batch_op.drop_column('has_garage')
        batch_op.drop_column('main_level_bathrooms')
        batch_op.drop_column('has_cooling')
        batch_op.drop_column('window_features')
        batch_op.drop_column('bedrooms')
        batch_op.drop_column('lat')
        batch_op.drop_column('is_new_construction')
        batch_op.drop_column('interior_features')
        batch_op.drop_column('photos')
        batch_op.drop_column('bathrooms_partial')
        batch_op.drop_column('year_built')
        batch_op.drop_column('schools')
        batch_op.drop_column('view')
        batch_op.drop_column('has_heating')
        batch_op.drop_column('commute_data')
        batch_op.drop_column('property_type')
        batch_op.drop_column('heating')
        batch_op.drop_column('bathrooms_three_quarter')
        batch_op.drop_column('contact_recipients')
        batch_op.drop_column('structure_type')
        batch_op.drop_column('zestimate')
        batch_op.drop_column('listing_status')
        batch_op.drop_column('zpid')
        batch_op.drop_column('price_history')
        batch_op.drop_column('tax_annual_amount')
        batch_op.drop_column('home_type')
        batch_op.drop_column('utilities')
        batch_op.drop_column('images')
        batch_op.drop_column('community_features')
        batch_op.drop_column('city_id')
        batch_op.drop_column('roof_type')
        batch_op.drop_column('city')
        batch_op.drop_column('has_view')
        batch_op.drop_column('rooms')
        batch_op.drop_column('state')
        batch_op.drop_column('home_status')
        batch_op.drop_column('annual_homeowners_insurance')
        batch_op.drop_column('county')
        batch_op.drop_column('subdivision_name')
        batch_op.drop_column('association_fee')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('property_condition')
        batch_op.drop_column('water_view')
        batch_op.drop_column('home_id')
        batch_op.drop_column('cooling')
        batch_op.drop_column('favorite_count')
        batch_op.drop_column('stories')
        batch_op.drop_column('bathrooms_half')
        batch_op.drop_column('zillow_url')
        batch_op.drop_column('subdivision')
        batch_op.drop_column('architectural_style')
        batch_op.drop_column('lot_features')
        batch_op.drop_column('listed_by')
        batch_op.drop_column('image_features')
        batch_op.drop_column('at_a_glance_facts')
        batch_op.drop_column('property_tax_rate')
        batch_op.drop_column('description')
        batch_op.drop_column('living_area_value')
        batch_op.drop_column('on_market_date')
        batch_op.drop_column('has_attached_garage')
        batch_op.drop_column('appliances')
        batch_op.drop_column('url')
        batch_op.drop_column('hoa_fee')
        batch_op.drop_column('construction_materials')
        batch_op.drop_column('building_name')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('price_per_square_foot')
        batch_op.drop_column('main_level_bedrooms')
        batch_op.drop_column('parking')
        batch_op.drop_column('mlsid')
        batch_op.drop_column('monthly_hoa_fee')
        batch_op.drop_column('garage_spaces')
        batch_op.drop_column('exterior_features')
        batch_op.drop_column('living_area')
        batch_op.drop_column('features')
        batch_op.drop_column('foundation_details')
        batch_op.drop_column('mortgage_rates')
        batch_op.drop_column('inclusions')
        batch_op.drop_column('street_address')
        batch_op.drop_column('has_fireplace')
        batch_op.drop_column('time_on_zillow')
        batch_op.drop_column('property_type_dimension')
        batch_op.drop_column('parking_features')
        batch_op.drop_column('nearby_homes')
        batch_op.drop_column('rent_zestimate')
        batch_op.drop_column('flooring')

        # 2) Now that existing rows are populated, enforce NOT NULL and drop the default
        batch_op.alter_column('user_id', nullable=False, server_default=None)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_homes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - unchanged except ordering ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_homes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('home_universal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flooring', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rent_zestimate', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nearby_homes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parking_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_type_dimension', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time_on_zillow', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_fireplace', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('street_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inclusions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mortgage_rates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foundation_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('living_area', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exterior_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('garage_spaces', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('monthly_hoa_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mlsid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parking', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('main_level_bedrooms', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_per_square_foot', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zipcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('building_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('construction_materials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hoa_fee', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('appliances', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_attached_garage', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('on_market_date', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('living_area_value', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('at_a_glance_facts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('listed_by', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lot_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('architectural_style', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subdivision', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zillow_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bathrooms_half', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stories', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cooling', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('water_view', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_condition', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('association_fee', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subdivision_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('county', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('annual_homeowners_insurance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rooms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_view', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('roof_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('community_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('utilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tax_annual_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zpid', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('listing_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zestimate', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('structure_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact_recipients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bathrooms_three_quarter', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('heating', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commute_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_heating', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('view', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('schools', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('year_built', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bathrooms_partial', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('photos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('interior_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_new_construction', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('window_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_cooling', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('main_level_bathrooms', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_garage', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page_view_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parcel_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_association', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('virtual_tour', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bathrooms_full', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('days_on_zillow', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('sqft',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('baths')
        batch_op.drop_column('beds')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('home_descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('negatives')
        batch_op.drop_column('positives')
        batch_op.drop_column('user_description')
    # ### end Alembic commands ###
