"""migrate

Revision ID: bd599f3198d5
Revises: 07fc3df465df
Create Date: 2026-04-02 00:58:53.140945

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bd599f3198d5"
down_revision = "07fc3df465df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use op.add_column (not batch_alter_table): batch mode can omit server_default on PostgreSQL,
    # which breaks NOT NULL adds when the table already has rows.
    op.add_column(
        "user_search_display",
        sa.Column(
            "preferences_strict_filter",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_search_display", "preferences_strict_filter")

    # ### end Alembic commands ###
