"""migrate

Revision ID: bf141de1c95e
Revises: a0a768474b70
Create Date: 2026-01-06 14:07:59.371048

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf141de1c95e"
down_revision = "a0a768474b70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_picture", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("mls_id", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("brokerage", sa.String(length=200), nullable=True))
        batch_op.drop_column("is_closing_mode")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_closing_mode", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("brokerage")
        batch_op.drop_column("mls_id")
        batch_op.drop_column("profile_picture")

    # ### end Alembic commands ###
