"""migrate

Revision ID: c2d903acebb0
Revises: 3ed605eee7e1
Create Date: 2026-02-16 15:14:43.773515

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2d903acebb0"
down_revision = "3ed605eee7e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agreements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agreements_current_revision_id"), ["current_revision_id"], unique=False
        )
        batch_op.create_foreign_key(
            None, "agreement_revisions", ["current_revision_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_request_status", sa.String(length=20), nullable=True))

    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("preferred_bedrooms_min", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("preferred_bedrooms_max", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("preferred_bathrooms_min", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("preferred_bathrooms_max", sa.Integer(), nullable=True))
        batch_op.drop_column("report_section_priorities")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_section_priorities", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("preferred_bathrooms_max")
        batch_op.drop_column("preferred_bathrooms_min")
        batch_op.drop_column("preferred_bedrooms_max")
        batch_op.drop_column("preferred_bedrooms_min")

    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.drop_column("event_request_status")

    with op.batch_alter_table("agreements", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_agreements_current_revision_id"))

    # ### end Alembic commands ###
