"""migrate

Revision ID: c3eb1c7805e4
Revises: 92c1d13e5453
Create Date: 2025-10-29 20:37:53.103193

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c3eb1c7805e4"
down_revision = "92c1d13e5453"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        batch_op.add_column(sa.Column("score", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        batch_op.drop_column("score")

    # ### end Alembic commands ###
