"""add_personalization_emotional_fields_and_user_has_preferences

Revision ID: d0f8c38966a9
Revises: 8834d3625782
Create Date: 2025-07-24 18:52:11.625291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f8c38966a9'
down_revision = '8834d3625782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solo_reports_created', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('solo_reports_addresses', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('group_reports_created', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('group_reports_addresses', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chat_sessions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_home_price_range', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('preferred_bathrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_bedrooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_home_features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('favored_information_style', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('intended_property_use', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('timeline_to_purchase', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_home_ownership_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('moving_reason', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('content_feedback_log', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('agent_interaction_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('personality_insights', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quote_bubbles', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deal_makers', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('concerns_or_fears', sa.Text(), nullable=True))
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('financial_goals')
        batch_op.drop_column('sustainability_importance')
        batch_op.drop_column('environmental_consciousness')
        batch_op.drop_column('follow_up_preference')
        batch_op.drop_column('response_time_expectation')
        batch_op.drop_column('current_housing_status')
        batch_op.drop_column('stress_level')
        batch_op.drop_column('price_sensitivity')
        batch_op.drop_column('data_sharing_comfort')
        batch_op.drop_column('loyalty_program_participation')
        batch_op.drop_column('service_expectations')
        batch_op.drop_column('tech_savviness')
        batch_op.drop_column('privacy_concern_level')
        batch_op.drop_column('dietary_restrictions')
        batch_op.drop_column('travel_frequency')
        batch_op.drop_column('social_causes_supported')
        batch_op.drop_column('sleep_schedule')
        batch_op.drop_column('social_media_usage')
        batch_op.drop_column('early_adopter_tendency')
        batch_op.drop_column('health_consciousness')
        batch_op.drop_column('security_awareness')
        batch_op.drop_column('online_shopping_frequency')
        batch_op.drop_column('debt_to_income_ratio')
        batch_op.drop_column('complaint_behavior')
        batch_op.drop_column('impulse_buying_tendency')
        batch_op.drop_column('entertainment_preferences')
        batch_op.drop_column('preferred_communication')
        batch_op.drop_column('device_preferences')
        batch_op.drop_column('preferred_property_size')
        batch_op.drop_column('current_housing_type')
        batch_op.drop_column('exercise_frequency')
        batch_op.drop_column('shopping_preferences')
        batch_op.drop_column('brand_loyalty')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_preferences', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_preferences')

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_loyalty', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('shopping_preferences', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exercise_frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_housing_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferred_property_size', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_preferences', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferred_communication', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('entertainment_preferences', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('impulse_buying_tendency', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('complaint_behavior', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('debt_to_income_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('online_shopping_frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('security_awareness', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('health_consciousness', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('early_adopter_tendency', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('social_media_usage', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sleep_schedule', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('social_causes_supported', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('travel_frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dietary_restrictions', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('privacy_concern_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tech_savviness', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_expectations', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('loyalty_program_participation', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_sharing_comfort', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_sensitivity', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stress_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_housing_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('response_time_expectation', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('follow_up_preference', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('environmental_consciousness', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sustainability_importance', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('financial_goals', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('concerns_or_fears')
        batch_op.drop_column('deal_makers')
        batch_op.drop_column('quote_bubbles')
        batch_op.drop_column('personality_insights')
        batch_op.drop_column('agent_interaction_history')
        batch_op.drop_column('content_feedback_log')
        batch_op.drop_column('moving_reason')
        batch_op.drop_column('current_home_ownership_status')
        batch_op.drop_column('timeline_to_purchase')
        batch_op.drop_column('intended_property_use')
        batch_op.drop_column('favored_information_style')
        batch_op.drop_column('preferred_home_features')
        batch_op.drop_column('preferred_bedrooms')
        batch_op.drop_column('preferred_bathrooms')
        batch_op.drop_column('preferred_home_price_range')
        batch_op.drop_column('chat_sessions')
        batch_op.drop_column('group_reports_addresses')
        batch_op.drop_column('group_reports_created')
        batch_op.drop_column('solo_reports_addresses')
        batch_op.drop_column('solo_reports_created')

    # ### end Alembic commands ###
