"""migrate

Revision ID: d322cd57307f
Revises: f785af99f54e
Create Date: 2026-01-13 15:24:30.050040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd322cd57307f'
down_revision = 'f785af99f54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first with server defaults for existing rows
    with op.batch_alter_table('user_google_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_userinfo_email', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('has_userinfo_profile', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('has_openid', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('has_calendar_freebusy', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('has_calendar_app_created', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('has_calendar_calendarlist_readonly', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('has_calendar_events_freebusy', sa.Boolean(), nullable=True, server_default='false'))
    
    # Update existing rows based on their scopes
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id, scopes FROM user_google_tokens"))
    rows = result.fetchall()
    
    for row in rows:
        token_id, scopes = row
        if not scopes:
            continue
        
        scope_list = scopes.split() if isinstance(scopes, str) else scopes
        
        # Build update statement with proper parameter binding
        update_parts = []
        params = {'token_id': token_id}
        
        if "https://www.googleapis.com/auth/userinfo.email" in scope_list:
            update_parts.append("has_userinfo_email = :has_userinfo_email")
            params['has_userinfo_email'] = True
        if "https://www.googleapis.com/auth/userinfo.profile" in scope_list:
            update_parts.append("has_userinfo_profile = :has_userinfo_profile")
            params['has_userinfo_profile'] = True
        if "openid" in scope_list:
            update_parts.append("has_openid = :has_openid")
            params['has_openid'] = True
        if "https://www.googleapis.com/auth/calendar.freebusy" in scope_list:
            update_parts.append("has_calendar_freebusy = :has_calendar_freebusy")
            params['has_calendar_freebusy'] = True
        if "https://www.googleapis.com/auth/calendar.app.created" in scope_list:
            update_parts.append("has_calendar_app_created = :has_calendar_app_created")
            params['has_calendar_app_created'] = True
        if "https://www.googleapis.com/auth/calendar.calendarlist.readonly" in scope_list:
            update_parts.append("has_calendar_calendarlist_readonly = :has_calendar_calendarlist_readonly")
            params['has_calendar_calendarlist_readonly'] = True
        if "https://www.googleapis.com/auth/calendar.events.freebusy" in scope_list:
            update_parts.append("has_calendar_events_freebusy = :has_calendar_events_freebusy")
            params['has_calendar_events_freebusy'] = True
        
        if update_parts:
            set_clause = ', '.join(update_parts)
            connection.execute(
                sa.text(f"UPDATE user_google_tokens SET {set_clause} WHERE id = :token_id"),
                params
            )
    
    # Now make columns NOT NULL
    with op.batch_alter_table('user_google_tokens', schema=None) as batch_op:
        batch_op.alter_column('has_userinfo_email', nullable=False, server_default=None)
        batch_op.alter_column('has_userinfo_profile', nullable=False, server_default=None)
        batch_op.alter_column('has_openid', nullable=False, server_default=None)
        batch_op.alter_column('has_calendar_freebusy', nullable=False, server_default=None)
        batch_op.alter_column('has_calendar_app_created', nullable=False, server_default=None)
        batch_op.alter_column('has_calendar_calendarlist_readonly', nullable=False, server_default=None)
        batch_op.alter_column('has_calendar_events_freebusy', nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_google_tokens', schema=None) as batch_op:
        batch_op.drop_column('has_calendar_events_freebusy')
        batch_op.drop_column('has_calendar_calendarlist_readonly')
        batch_op.drop_column('has_calendar_app_created')
        batch_op.drop_column('has_calendar_freebusy')
        batch_op.drop_column('has_openid')
        batch_op.drop_column('has_userinfo_profile')
        batch_op.drop_column('has_userinfo_email')

    # ### end Alembic commands ###
