"""migrate

Revision ID: d7ff5b8c2ce5
Revises: 5bdb3e4ae894
Create Date: 2026-01-02 17:54:10.782144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ff5b8c2ce5'
down_revision = '5bdb3e4ae894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('agent_interaction_history')
        batch_op.drop_column('personality_insights')
        batch_op.drop_column('additional_context')
        batch_op.drop_column('content_feedback_log')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_feedback_log', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('additional_context', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('personality_insights', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('agent_interaction_history', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
