"""migrate

Revision ID: d89a75e6977f
Revises: dfa6824d6cbd
Create Date: 2026-01-03 12:12:47.132766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd89a75e6977f'
down_revision = 'dfa6824d6cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop the foreign key constraint and alter the column type
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint('calendar_events_calendar_id_fkey', type_='foreignkey')
        batch_op.alter_column('calendar_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=True)
    
    # Now we can safely drop the calendars table
    op.drop_table('calendars')

    with op.batch_alter_table('user_google_tokens', schema=None) as batch_op:
        batch_op.drop_column('client_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, recreate the calendars table
    op.create_table('calendars',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('calendar_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('google_calendar_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('calendar_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_synced', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sync_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('calendars_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calendars_pkey'))
    )
    
    # Then alter calendar_events to restore the foreign key
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.alter_column('calendar_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.create_foreign_key('calendar_events_calendar_id_fkey', 'calendars', ['calendar_id'], ['id'])

    with op.batch_alter_table('user_google_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
