"""Refactor to_dict for onboarding fields only

Revision ID: d9631abfec2a
Revises: f9da91fb8590
Create Date: 2025-08-05 18:04:41.753691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9631abfec2a'
down_revision = 'f9da91fb8590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intended_property_use', sa.String(length=100), nullable=True))
        batch_op.drop_column('concerns_or_fears')
        batch_op.drop_column('communication_preference')
        batch_op.drop_column('property_features_priority')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_features_priority', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('communication_preference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('concerns_or_fears', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('intended_property_use')

    # ### end Alembic commands ###
