"""Add report customization preferences

Revision ID: dbe77c1ab14f
Revises: 4054dd28ff69
Create Date: 2025-07-25 13:54:21.358732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe77c1ab14f'
down_revision = '4054dd28ff69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_neighborhood_overview', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_safety', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_culture_and_events', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_weather', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_social_character', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_local_amenities', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_commute', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_family_friendly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_nightlife_and_dating', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_accessibility', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_development', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_environment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_money', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_schools', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_extra_tips', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('include_extra_tips')
        batch_op.drop_column('include_schools')
        batch_op.drop_column('include_money')
        batch_op.drop_column('include_environment')
        batch_op.drop_column('include_development')
        batch_op.drop_column('include_accessibility')
        batch_op.drop_column('include_nightlife_and_dating')
        batch_op.drop_column('include_family_friendly')
        batch_op.drop_column('include_commute')
        batch_op.drop_column('include_local_amenities')
        batch_op.drop_column('include_social_character')
        batch_op.drop_column('include_weather')
        batch_op.drop_column('include_culture_and_events')
        batch_op.drop_column('include_safety')
        batch_op.drop_column('include_neighborhood_overview')

    # ### end Alembic commands ###
