"""Refactor to_dict for onboarding fields only

Revision ID: e52192f4d544
Revises: b59fd3e8a725
Create Date: 2025-08-06 22:07:20.142860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52192f4d544'
down_revision = 'b59fd3e8a725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_home_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_home_ids')

    # ### end Alembic commands ###
