"""migrate

Revision ID: e7a561d22190
Revises: bf141de1c95e
Create Date: 2026-01-06 15:47:02.589518

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e7a561d22190"
down_revision = "bf141de1c95e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("target_user_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("shared_with_user_ids", sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, "users", ["target_user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("shared_with_user_ids")
        batch_op.drop_column("target_user_id")

    # ### end Alembic commands ###
