"""Refactor to_dict for onboarding fields only

Revision ID: ed30cd95a326
Revises: 15bf956a983a
Create Date: 2025-08-08 15:37:02.436780

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ed30cd95a326"
down_revision = "15bf956a983a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("reports_available")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reports_available", sa.INTEGER(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
