"""models going into folders

Revision ID: f4b9d44a2744
Revises: d89a75e6977f
Create Date: 2026-01-05 14:51:33.445131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b9d44a2744'
down_revision = 'd89a75e6977f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_at', sa.Text(), nullable=True))

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_by', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('was_read', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('was_read')
        batch_op.drop_column('read_at')
        batch_op.drop_column('read_by')

    with op.batch_alter_table('agent_conversations', schema=None) as batch_op:
        batch_op.drop_column('last_read_at')

    # ### end Alembic commands ###
