"""search changes

Revision ID: f785af99f54e
Revises: e7a561d22190
Create Date: 2026-01-08 10:01:40.259018

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f785af99f54e"
down_revision = "e7a561d22190"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("current", sa.Boolean(), server_default=sa.text("true"), nullable=False)
        )
        batch_op.add_column(sa.Column("ranking", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("home_universal", schema=None) as batch_op:
        batch_op.drop_column("ranking")
        batch_op.drop_column("current")

    # ### end Alembic commands ###
