"""migrate

Revision ID: f9cbadcc8e55
Revises: 42049c945e9d
Create Date: 2025-10-28 15:39:08.430985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cbadcc8e55'
down_revision = '42049c945e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subscriptions_stripe_customer_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('subscriptions_stripe_subscription_id_key'), type_='unique')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('stripe_subscription_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_logged_in', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('last_logged_in')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('subscriptions_stripe_subscription_id_key'), ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('subscriptions_stripe_customer_id_key'), ['stripe_customer_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
