"""Update user preferences fields

Revision ID: f9da91fb8590
Revises: 4d9e2babcd55
Create Date: 2025-08-05 17:58:19.629988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9da91fb8590'
down_revision = '4d9e2babcd55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pets', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gross_income', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('home_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('down_payment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ideal_zip_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('housing_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('renovation_preference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('architectural_style_preference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_buyers_agent', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('looking_for_buyers_agent', sa.Boolean(), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('preferred_lot_size',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('preferred_home_age',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('preferred_architectural_style',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('commute_tolerance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('walkability_importance',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('communication_preference',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('communication_frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('information_detail_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('children_ages')
        batch_op.drop_column('children_count')
        batch_op.drop_column('savings_amount_range')
        batch_op.drop_column('research_behavior')
        batch_op.drop_column('intended_property_use')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('current_home_ownership_status')
        batch_op.drop_column('financing_preference')
        batch_op.drop_column('preferred_climate')
        batch_op.drop_column('desired_housing_type')
        batch_op.drop_column('renovation_willingness')
        batch_op.drop_column('property_search_stage')
        batch_op.drop_column('moving_reason')
        batch_op.drop_column('deal_makers')
        batch_op.drop_column('household_size')
        batch_op.drop_column('dining_preferences')
        batch_op.drop_column('risk_tolerance')
        batch_op.drop_column('fitness_activities')
        batch_op.drop_column('community_involvement')
        batch_op.drop_column('urban_rural_preference')
        batch_op.drop_column('income_range')
        batch_op.drop_column('political_leaning')
        batch_op.drop_column('home_buying_experience')
        batch_op.drop_column('hobbies_interests')
        batch_op.drop_column('timeline_to_purchase')
        batch_op.drop_column('meeting_availability')
        batch_op.drop_column('quote_bubbles')
        batch_op.drop_column('preferred_support_channel')
        batch_op.drop_column('lifestyle_type')
        batch_op.drop_column('education_level')
        batch_op.drop_column('preferred_home_price_range')
        batch_op.drop_column('proximity_to_family')
        batch_op.drop_column('favored_information_style')
        batch_op.drop_column('decision_making_style')
        batch_op.drop_column('industry')
        batch_op.drop_column('investment_experience')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('meeting_preference')
        batch_op.drop_column('response_time_expectation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time_expectation', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meeting_preference', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('investment_experience', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('decision_making_style', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favored_information_style', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('proximity_to_family', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferred_home_price_range', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('education_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lifestyle_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferred_support_channel', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quote_bubbles', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meeting_availability', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timeline_to_purchase', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hobbies_interests', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home_buying_experience', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('political_leaning', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('income_range', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('urban_rural_preference', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('community_involvement', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fitness_activities', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('risk_tolerance', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dining_preferences', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('household_size', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deal_makers', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('moving_reason', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_search_stage', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('renovation_willingness', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('desired_housing_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferred_climate', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('financing_preference', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_home_ownership_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('intended_property_use', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('research_behavior', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('savings_amount_range', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('children_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('children_ages', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('information_detail_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('communication_frequency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('communication_preference',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('walkability_importance',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('commute_tolerance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('preferred_architectural_style',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('preferred_home_age',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('preferred_lot_size',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('looking_for_buyers_agent')
        batch_op.drop_column('has_buyers_agent')
        batch_op.drop_column('architectural_style_preference')
        batch_op.drop_column('renovation_preference')
        batch_op.drop_column('housing_type')
        batch_op.drop_column('ideal_zip_code')
        batch_op.drop_column('down_payment')
        batch_op.drop_column('home_budget')
        batch_op.drop_column('gross_income')
        batch_op.drop_column('pets')

    # ### end Alembic commands ###
