"""Make user name nullable for Google OAuth users

Revision ID: j9k0l1m2n3o4
Revises: i8j9k0l1m2n3
Create Date: 2025-10-16 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'j9k0l1m2n3o4'
down_revision = 'i8j9k0l1m2n3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Make name column nullable to support Google OAuth users who may not have a name
        batch_op.alter_column('name',
                              existing_type=sa.String(length=100),
                              nullable=True)
        
        # Make phone column explicitly nullable (it already was, but making it explicit)
        batch_op.alter_column('phone',
                              existing_type=sa.String(length=20),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Set a default value for any NULL names before reverting to NOT NULL
    # Use email prefix as fallback for users without names
    op.execute("""
        UPDATE users 
        SET name = COALESCE(
            name, 
            SUBSTRING(email FROM 1 FOR POSITION('@' IN email) - 1)
        ) 
        WHERE name IS NULL OR name = ''
    """)
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Revert name to NOT NULL (this will now work since we set defaults above)
        batch_op.alter_column('name',
                              existing_type=sa.String(length=100),
                              nullable=False)

    # ### end Alembic commands ###

