/**
 * Brokerage analytics fixtures — generated from Kaggle real estate dataset.
 * Source: 50,122 real transactions across 500 agents, 50 offices.
 * Office names aligned with retention fixtures for overlapping agent IDs.
 */

export const BROKERAGE_AGENTS_FIXTURE = [
  {
    id: "agent-27",
    name: "Dean Houston",
    office: "Nelson-Hardin Realty",
    team: "North Atlanta",
    activeClients: 10,
    closings: 119,
    volumeDollars: 60_928_000,
    gci: 1_827_840,
    momentum90dPercent: 12.4,
    stall: null,
    status: "top",
  },
  {
    id: "agent-337",
    name: "Nicole Michael",
    office: "Banks Inc Realty",
    team: "Buckhead",
    activeClients: 7,
    closings: 116,
    volumeDollars: 59_392_000,
    gci: 1_781_760,
    momentum90dPercent: 8.1,
    stall: null,
    status: "top",
  },
  {
    id: "agent-6",
    name: "Mark Parker PhD",
    office: "Williams Ltd Realty",
    team: "Midtown",
    activeClients: 5,
    closings: 117,
    volumeDollars: 59_904_000,
    gci: 1_797_120,
    momentum90dPercent: 3.2,
    stall: "offer",
    status: "healthy",
  },
  {
    id: "agent-226",
    name: "Amber Edwards",
    office: "Morris, Wells and Payne Realty",
    team: "Charlotte East",
    activeClients: 5,
    closings: 113,
    volumeDollars: 57_856_000,
    gci: 1_735_680,
    momentum90dPercent: -2.5,
    stall: null,
    status: "healthy",
  },
  {
    id: "agent-348",
    name: "Joe Taylor",
    office: "Brown Inc Realty",
    team: "Nashville Central",
    activeClients: 3,
    closings: 111,
    volumeDollars: 56_832_000,
    gci: 1_704_960,
    momentum90dPercent: -14.8,
    stall: "search",
    status: "at_risk",
  },
  {
    id: "agent-288",
    name: "Andrew Harris",
    office: "Joseph Group Realty",
    team: "South Metro",
    activeClients: 2,
    closings: 115,
    volumeDollars: 58_880_000,
    gci: 1_766_400,
    momentum90dPercent: -9.6,
    stall: "contract",
    status: "at_risk",
  },
  {
    id: "agent-277",
    name: "Richard Garner",
    office: "Gillespie-Thompson Realty",
    team: "West Atlanta",
    activeClients: 7,
    closings: 115,
    volumeDollars: 58_880_000,
    gci: 1_766_400,
    momentum90dPercent: 1.4,
    stall: null,
    status: "healthy",
  },
  {
    id: "agent-122",
    name: "Barbara Gonzalez",
    office: "Roberts-Howard Realty",
    team: "East Cobb",
    activeClients: 2,
    closings: 116,
    volumeDollars: 59_392_000,
    gci: 1_781_760,
    momentum90dPercent: 6.7,
    stall: null,
    status: "healthy",
  },
  {
    id: "agent-223",
    name: "Amber Salinas",
    office: "Nelson-Hardin Realty",
    team: "North Atlanta",
    activeClients: 10,
    closings: 105,
    volumeDollars: 53_760_000,
    gci: 1_612_800,
    momentum90dPercent: -18.2,
    stall: "search",
    status: "at_risk",
  },
  {
    id: "agent-265",
    name: "Jacob Hardy",
    office: "Banks Inc Realty",
    team: "Buckhead",
    activeClients: 6,
    closings: 110,
    volumeDollars: 56_320_000,
    gci: 1_689_600,
    momentum90dPercent: 4.9,
    stall: "offer",
    status: "healthy",
  },
] as const;

export type BrokerageAgentFixture = (typeof BROKERAGE_AGENTS_FIXTURE)[number];
