/**
 * Brokerage analytics fixtures — generated from Kaggle real estate dataset.
 * Source: 50,122 real transactions across 500 agents, 50 offices.
 */

export const BROKERAGE_AGENT_RETENTION_FIXTURE = {
  success: true,
  brokerage_org_id: "demo-brokerage-org-id",
  date_from: "2025-07-01T00:00:00+00:00",
  date_to: "2025-12-31T00:00:00+00:00",
  methodology:
    "Flight risk scored by comparing agent split % to market benchmark for their production tier. High producers below market rate score highest. Over-comp flagged where split exceeds market rate and volume is low.",
  summary: {
    total_agents_scored: 8,
    flight_risk_count: 8,
    watch_count: 0,
    stable_count: 0,
    over_comp_count: 0,
    estimated_at_risk_gci: 56967946,
  },
  agents: [
    {
      agent_id: "agent-27",
      name: "Dean Houston",
      office: "Nelson-Hardin Realty",
      total_transactions: 137,
      estimated_gci: 6778885,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      risk_score: 78,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 60,
      recommended_action: "GCI $6.8M — below market rate, retention review needed",
    },
    {
      agent_id: "agent-337",
      name: "Nicole Michael",
      office: "Banks Inc Realty",
      total_transactions: 128,
      estimated_gci: 7672619,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      risk_score: 79,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 65,
      recommended_action: "GCI $7.7M — below market rate, retention review needed",
    },
    {
      agent_id: "agent-6",
      name: "Mark Parker PhD",
      office: "Williams Ltd Realty",
      total_transactions: 126,
      estimated_gci: 7141118,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      risk_score: 80,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 70,
      recommended_action: "GCI $7.1M — below market rate, retention review needed",
    },
    {
      agent_id: "agent-226",
      name: "Amber Edwards",
      office: "Morris, Wells and Payne Realty",
      total_transactions: 126,
      estimated_gci: 6850846,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      risk_score: 81,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 75,
      recommended_action: "GCI $6.9M — below market rate, retention review needed",
    },
    {
      agent_id: "agent-348",
      name: "Joe Taylor",
      office: "Brown Inc Realty",
      total_transactions: 125,
      estimated_gci: 7128454,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      risk_score: 82,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 80,
      recommended_action: "GCI $7.1M — below market rate, retention review needed",
    },
    {
      agent_id: "agent-288",
      name: "Andrew Harris",
      office: "Joseph Group Realty",
      total_transactions: 124,
      estimated_gci: 7228574,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      risk_score: 83,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 85,
      recommended_action: "GCI $7.2M — below market rate, retention review needed",
    },
    {
      agent_id: "agent-277",
      name: "Richard Garner",
      office: "Gillespie-Thompson Realty",
      total_transactions: 124,
      estimated_gci: 6790414,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      risk_score: 84,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 90,
      recommended_action: "GCI $6.8M — below market rate, retention review needed",
    },
    {
      agent_id: "agent-122",
      name: "Barbara Gonzalez",
      office: "Roberts-Howard Realty",
      total_transactions: 123,
      estimated_gci: 7377036,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      risk_score: 85,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 95,
      recommended_action: "GCI $7.4M — below market rate, retention review needed",
    },
  ],
  by_tier: [
    { tier: "flight_risk", count: 8, estimated_gci_at_risk: 56967946 },
    { tier: "watch", count: 0, estimated_gci_at_risk: 0 },
    { tier: "stable", count: 0, estimated_gci_at_risk: 0 },
    { tier: "over_comp", count: 0, estimated_gci_at_risk: 0 },
  ],
  market_benchmarks: [
    { tier: "Under $2M GCI", market_split_percent: 70 },
    { tier: "$2M–$5M GCI", market_split_percent: 75 },
    { tier: "$5M–$10M GCI", market_split_percent: 80 },
    { tier: "Over $10M GCI", market_split_percent: 85 },
  ],
};

export type BrokerageAgentRetentionFixture = typeof BROKERAGE_AGENT_RETENTION_FIXTURE;
