/**
 * Brokerage analytics fixtures — agent retention risk (coaching subset).
 * Agent IDs/names aligned with BROKERAGE_AGENTS_FIXTURE (monthly baselines).
 *
 * Flight risk is a blended ML score: equal-weight mean of five factor scores.
 * Split fields remain as supporting detail for the compensation factor only.
 */

export const BROKERAGE_AGENT_RETENTION_FIXTURE = {
  success: true,
  brokerage_org_id: "demo-brokerage-org-id",
  date_from: "2025-07-01T00:00:00+00:00",
  date_to: "2025-12-31T00:00:00+00:00",
  methodology:
    "Flight risk is a blended ML score (0-100) from five equal-weight factors: comp competitiveness, production momentum, peer standing, engagement, and ancillary attach. Split vs market informs the compensation factor only. Over-comp is flagged when compensation risk is high while production and peer standing are low.",
  summary: {
    total_agents_scored: 8,
    flight_risk_count: 6,
    watch_count: 1,
    stable_count: 1,
    over_comp_count: 0,
    estimated_at_risk_gci: 161_433,
  },
  agents: [
    {
      agent_id: "AGT-0460",
      name: "Robin Pittman",
      office: "Downtown Office",
      total_transactions: 4,
      estimated_gci: 27_457,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      factor_scores: {
        compensation: 85,
        production_momentum: 72,
        peer_standing: 70,
        engagement: 80,
        ancillary_attach: 83,
      },
      risk_score: 78,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 60,
      recommended_action:
        "High blended risk: compensation and attach gaps leading; schedule retention + title/lending check-in",
    },
    {
      agent_id: "AGT-0343",
      name: "Kristina Alexander",
      office: "East Office",
      total_transactions: 4,
      estimated_gci: 29_373,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      factor_scores: {
        compensation: 86,
        production_momentum: 74,
        peer_standing: 72,
        engagement: 80,
        ancillary_attach: 83,
      },
      risk_score: 79,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 65,
      recommended_action:
        "High blended risk: comp competitiveness and ancillary attach driving score; retention review",
    },
    {
      agent_id: "AGT-0372",
      name: "Brittney Collins",
      office: "North Office",
      total_transactions: 4,
      estimated_gci: 25_249,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      factor_scores: {
        compensation: 88,
        production_momentum: 76,
        peer_standing: 74,
        engagement: 78,
        ancillary_attach: 84,
      },
      risk_score: 80,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 70,
      recommended_action:
        "High blended risk: compensation gap and weak momentum; offer split review and coaching",
    },
    {
      agent_id: "AGT-0276",
      name: "John Martin",
      office: "West Office",
      total_transactions: 4,
      estimated_gci: 24_215,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      factor_scores: {
        compensation: 88,
        production_momentum: 78,
        peer_standing: 76,
        engagement: 80,
        ancillary_attach: 83,
      },
      risk_score: 81,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 75,
      recommended_action:
        "High blended risk across compensation and engagement; proactive retention outreach",
    },
    {
      agent_id: "AGT-0323",
      name: "Sara Spencer",
      office: "Downtown Office",
      total_transactions: 4,
      estimated_gci: 28_214,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      factor_scores: {
        compensation: 90,
        production_momentum: 80,
        peer_standing: 78,
        engagement: 82,
        ancillary_attach: 80,
      },
      risk_score: 82,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 80,
      recommended_action:
        "High blended risk: top drivers are compensation and engagement; retention split review",
    },
    {
      agent_id: "AGT-0341",
      name: "Robert Tate",
      office: "Buckhead Office",
      total_transactions: 4,
      estimated_gci: 26_925,
      current_split_percent: 72,
      market_benchmark_split_percent: 80,
      split_gap: -8,
      factor_scores: {
        compensation: 92,
        production_momentum: 82,
        peer_standing: 80,
        engagement: 84,
        ancillary_attach: 77,
      },
      risk_score: 83,
      risk_tier: "flight_risk" as const,
      peer_production_percentile: 85,
      recommended_action:
        "Highest blended risk: compensation and peer standing elevated; immediate retention review",
    },
    {
      agent_id: "AGT-0014",
      name: "Janet Patrick",
      office: "South Office",
      total_transactions: 4,
      estimated_gci: 28_593,
      current_split_percent: 78,
      market_benchmark_split_percent: 80,
      split_gap: -2,
      factor_scores: {
        compensation: 48,
        production_momentum: 40,
        peer_standing: 44,
        engagement: 38,
        ancillary_attach: 40,
      },
      risk_score: 42,
      risk_tier: "watch" as const,
      peer_production_percentile: 90,
      recommended_action:
        "Moderate blended risk: monitor engagement and momentum; revisit at next review cycle",
    },
    {
      agent_id: "AGT-0053",
      name: "Hector Dyer",
      office: "East Office",
      total_transactions: 4,
      estimated_gci: 27_250,
      current_split_percent: 80,
      market_benchmark_split_percent: 80,
      split_gap: 0,
      factor_scores: {
        compensation: 16,
        production_momentum: 20,
        peer_standing: 18,
        engagement: 16,
        ancillary_attach: 20,
      },
      risk_score: 18,
      risk_tier: "stable" as const,
      peer_production_percentile: 95,
      recommended_action: "Low blended risk across all factors; no retention action needed",
    },
  ],
  by_tier: [
    { tier: "flight_risk", count: 6, estimated_gci_at_risk: 161_433 },
    { tier: "watch", count: 1, estimated_gci_at_risk: 28_593 },
    { tier: "stable", count: 1, estimated_gci_at_risk: 0 },
    { tier: "over_comp", count: 0, estimated_gci_at_risk: 0 },
  ],
};

export type BrokerageAgentRetentionFixture = typeof BROKERAGE_AGENT_RETENTION_FIXTURE;
