/**
 * Pool of 100 sample comments for feed/reels (reference/placeholder use).
 * Not used to fake the comments sheet; sheet shows only real API comments.
 */

export const FEED_COMMENT_POOL: readonly string[] = [
  "Love this one!",
  "That kitchen though",
  "Need to see this in person",
  "Dream home material",
  "The backyard is everything",
  "So much natural light",
  "Perfect for a family",
  "Location is unbeatable",
  "Adding this to my list",
  "That porch!",
  "Can't get over the finishes",
  "Worth every penny",
  "When can we tour?",
  "The master bath is goals",
  "Great neighborhood",
  "This is the one",
  "Stunning views",
  "Love the open floor plan",
  "Pool party at my place",
  "The garage space is huge",
  "Schools nearby are top rated",
  "Walk to coffee and parks",
  "Quiet street, big lot",
  "Move-in ready",
  "That fireplace!",
  "So much character",
  "Modern but cozy",
  "The listing doesn't do it justice",
  "Already imagining holidays here",
  "Best one I've seen today",
  "Saving this for sure",
  "Price is right for the area",
  "HOA includes pool and gym",
  "Corner lot with extra privacy",
  "Updated electrical and HVAC",
  "The office nook is perfect",
  "Laundry room upstairs, finally",
  "Mudroom for the kids",
  "Chef's kitchen",
  "Built-ins everywhere",
  "Hardwood throughout",
  "New roof and windows",
  "Low maintenance yard",
  "Mature trees and shade",
  "Fenced for the dog",
  "Two living areas",
  "Formal dining plus eat-in",
  "Primary on main",
  "Guest suite downstairs",
  "Bonus room could be a gym",
  "Storage for days",
  "Attic and basement",
  "Driveway fits four cars",
  "No through traffic",
  "Close to the highway",
  "Bike trail at the end of the block",
  "Restaurants and shops nearby",
  "Safe and friendly",
  "Great for first-time buyers",
  "Or downsizers",
  "Investment potential",
  "Rental comps are strong",
  "Taxes are reasonable",
  "No flood zone",
  "Good resale history",
  "Seller is motivated",
  "Just listed",
  "Open house this weekend",
  "Bring your agent",
  "Worth a look",
  "Can't believe it's still available",
  "Pictures don't do it justice",
  "Better in person",
  "Already getting offers",
  "Price just dropped",
  "Motivated seller",
  "Estate sale",
  "Must see",
  "One of a kind",
  "Rare find",
  "Don't sleep on this one",
  "Top of my list",
  "Comparing a few but this stands out",
  "The layout is so functional",
  "Natural light in every room",
  "Low HOA",
  "No special assessment",
  "Recently renovated",
  "Turnkey",
  "Just my style",
  "Could see us here for years",
  "Checking with my lender",
  "Scheduling a showing",
  "Sent to my partner",
  "This might be the one",
  "Keeping an eye on it",
  "Hope it's still available",
  "Perfect size",
  "Not too big, not too small",
  "Exactly what we've been looking for",
  "The neighborhood feels right",
  "Good vibes only",
  "Would make a great home",
  "Already mentally moving in",
  "Counting down to the tour",
];
